//Grade 7
const G7C1 = [
  "Aimee | 刘妍汐",
  "Alex | 卓志俊",
  "Angela | 朱叶泉",
  "Anna | 罗宇轩",
  "Bailey | 黄冬扬",
  "Bryant | 陈子贤",
  "Cynthia | 赵千陌",
  "Darren | 熊彦彰",
  "Doris | 李忆蓝",
  "Eric | 易佳豪",
  "Guanzhen | 李冠臻",
  "Haobang | 郑皓帮",
  "Ivan | 赵天羿",
  "Ivy | 谢嘉洁",
  "Jackle | 乔荣康",
  "Jacky | 刘浩然",
  "Jessica | 方子嘉",
  "Karan | 陈可滢",
  "Kenny | 王梓宣",
  "Kenson | 叶司瀚",
  "Kitty | 黄子仪",
  "Kobe | 张景治",
  "Man | 王艺渊",
  "Marvin | 马文畅",
  "Miki | 陈妙苒",
  "Minnie | 陈乐彤",
  "Mona | 刘思语",
  "Monica | 汪梓菡",
  "Paul | 庞博  ",
  "Raymond | 刘睿泽",
  "Ruihan | 于睿涵",
  "Simple | 文兆轩",
  "Steven | 徐志宏",
  "Vincent | 林琸潇",
  "Yoo | 王语杨",
  "Zina | 黄琬淇"
];

const G7C2 = [
  "Andrea | 姚景暄",
  "Baby | 董怀恩",
  "Bella | 邢可佳",
  "Ben | 孙嘉沐",
  "Betty | 钟恩乐",
  "Chénziyì | 陈子逸",
  "David | 邓佳洪",
  "Dominic | 陈梓越",
  "Eddy | 刘奕潇",
  "Eleven | 杜林萱",
  "Emily | 冯子逸",
  "Jason | 尹家兴",
  "Jenny | 李佳霓",
  "Kenneth | 华俊翔",
  "Kim | 许嘉轩",
  "Kimi | 杨航 ",
  "Lily | 李紫芸",
  "Lulu | 张璐 ",
  "Lydeain | 常宸菲",
  "Mandy | 蔡馥蔓",
  "Max | 马煜轩",
  "Nadia | 黄玥涵",
  "Ocean | 邓博涵",
  "Peiyu | 甘培煜",
  "Plastic-Bag | 冯沛欣 ",
  "Ricky | 肖嘉轩",
  "Roy | 刘偌希",
  "Sam | 赵烽棋",
  "Siyi | 黄思怡",
  "Taihe | 吴泰和",
  "Tracy | 柳宣如",
  "Wenkang | 张文康",
  "Win | 黎致蓥",
  "Xinxin | 张馨心",
  "Yingqian | 叶颖谦",
  "Yuyan | 郁言 "
];

const G7C3 = [
  "Andy         | 魏子愚 ",
  "Angelia      | 郑可心 ",
  "Billy        | 张润瑄 ",
  "Bruce        | 范奕昊 ",
  "Caesar       | 蔡熙 ",
  "Ceiling      | 洪浠琳 ",
  "Chloe        | 胡馨睿 ",
  "Chong        | 许嘉翀 ",
  "Cici         | 曾乐儿 ",
  "Claire       | 陈奕臻 ",
  "CocoT        | 吴雨欣 ",
  "Daisy        | 叶岱灵 ",
  "Daniel       | 刘倬恺 ",
  "Edison       | 蓝野 ",
  "Emily        | 叶馨彤 ",
  "Fiona        | 范语菲 ",
  "Hang         | 李雨航 ",
  "Hannah       | 郭梓涵 ",
  "Huang        | 黄应中 ",
  "Jack         | 周裕洋 ",
  "Janice       | 李嘉荷 ",
  "Jeffrey      | 潘知远 ",
  "Jenny        | 黄恋茹 ",
  "Kai          | 霍恩恺 ",
  "Kelly        | 李雨函 ",
  "Kevin        | 罗凯辰 ",
  "Leslie       | 邓禹乐 ",
  "Lily         | 周子熙 ",
  "Oscar        | 黄梓洋 ",
  "Qi           | 傅畦之 ",
  "Rain         | 杜雨洋 ",
  "Renee        | 李雨璇 ",
  "Sissi        | 毛语熙 ",
  "Tiger        | 郭柏城 ",
  "Venus        | 温芷懿 ",
  "Xiao         | 肖睿轩 ",
  "Evia         | 张涵伊 ",
  "Yolanda      | 董培渝 ",
  "Yu           | 刘广宇 "
];

const G7C4 = [
"Abby | 智语轩",
"Ada | 陈嘉璇",
"Alex Guo | 郭佩鑫",
"Alex Wu | 吴煜哲",
"Alice | 邹沅芷",
"Amy | 罗宇泓",
"Andy Ma | 马铭俊",
"Andy Zheng | 郑智华",
"Annie | 邹和桉",
"Billy | 刘昊霆",
"Camellia | 王紫萱",
"Caroline | 陈妤越",
"Coco | 饶子滢",
"Elsa | 马怡然",
"Elsie | 温烨馨",
"Hugo | 郑汶昊",
"Hulk | 陈梓浩",
"Jessica | 曹婉宁",
"John | 曾瑞  ",
"Kenny | 钟睿邦",
"Kevin | 吴卓毅",
"Lemon | 游柠璐",
"Leo | 淦子邀",
"Teresa | 邓丽慈",
"Lily | 梁紫欣",
"Mia | 曾茗  ",
"Nick | 朱家尧",
"Nico | 李怡乐",
"Paddy | 严伟哲",
"Sam | 郭旭晨",
"Sofia | 张舒涵",
"Stephen | 董博文",
"Tom | 林华涛",
"William Wang | 汪敏皓",
"William Wen | 文俊哲",
"Yuki | 梁钰淇"
];

const G7C5 = [
"Abby | 简竹君",
"Aemy | 刘依诺",
"Aimee | 罗亦葭",
"Amy | 李妍兮",
"Amy | 张欣怡",
"Andy | 刘子轩",
"Angela | 刘芷萌",
"Annie | 黄梓宁",
"Cindy | 张昕曈",
"Corry | 徐哲宁",
"Doreen | 张雅轩",
"Eric Fu | 富雨轩",
"Eric Guo | 郭昊明",
"Ethan | 张竣轶",
"Irene | 丘若霖",
"Jack | 叶梓铭",
"Jane | 文心琪",
"Jerry | 高逸明",
"Jim | 王昱超",
"Katherine | 王瀚淇",
"Kenneth | 洪义康",
"Kiki | 黄灵熙",
"Kimi | 占云逸",
"Linda | 李梓涵",
"Ocean | 尹子龙",
"Paul | 王梓铭",
"Pear | 肖瑞雅",
"Rachel | 王梓睿",
"Ricky | 袁瑞泽",
"Simon | 尹曦禾",
"Terb | 方品涵",
"Vicky | 林语津",
"Yuhao | 梁钰浩",
"Ziming | 赵子铭"
];

const G7C6 = [
"Alysa | 李晓桐",
"Amy | 盛思书",
"Annie | 莫谨榕",
"Aven | 陈煜希",
"Brian | 杨博睿",
"Coco | 李米  ",
"Doris | 杨子萱",
"Elaine | 柯以贤",
"Ellie | 马兴蕾",
"Ethan | 李嘉巍",
"Felix | 汤济成",
"Helen | 邓禾  ",
"Hendy | 赵启恒",
"Hubery | 陈伟杰",
"Hyman | 洪浩铭",
"Isabella | 周永昕",
"Isla | 崔禾瑾",
"Jason | 余卓朗",
"Jemimah | 胡慧心",
"Jimmy | 王天穗",
"Joy | 蔡宇熙",
"Kevin | 李树豪",
"Larry | 王子乐",
"Leon | 周子渝",
"Marry | 朱璇  ",
"Max | 杨煜熙",
"Mora | 王炎舒",
"Ray | 宋睿轩",
"Ryan | 赵惊远",
"Susie | 郑舒兮",
"Timmy | 廖泓宇",
"Tommy | 崔添铭",
"Tony | 肖泓宇",
"Vincent | 王浩鑫",
"Yiming | 陈奕鸣",
"Yoyo | 沈灿辰",
"Zimo | 冉子墨"
];

const G7C7 = [
"Allen | 曾浚朗",
"Amy | 莫倩霖",
"Andy | 刘浩涵",
"Angeline | 许婼晴",
"Annie | 郑奕霏",
"Bell | 陈煜豪",
"Bella | 王子墨",
"Candice | 李嘉桐",
"Cassie | 陈雅晴",
"Cindy | 伍桐昕",
"Clarence | 杨皓然",
"Cosmo | 郭子墨",
"Daisy | 黄嘉雯",
"Darren | 刘润明",
"Elsa | 石展嘉",
"Elsa | 姚蕴芯",
"Eric | 张灏铖",
"Felix | 叶梓诚",
"Flower | 黄沛菡",
"Hiphop Man | 陈元浩",
"Hoshi | 李雅妍",
"Jason | 吴中超",
"Jenny | 周欣雨",
"Kerwin | 黄彦凯",
"Kevin | 冯晓光",
"Kris | 聂小涛",
"Laura | 刘芷玥",
"Linda | 林子晗",
"Ludi | 钟子阳",
"Marcus | 王彦瑜",
"Phoebe | 易婧纯",
"Sophy | 张心然",
"Terry | 郑毅添",
"Tiger | 陈禹廷",
"Usi | 苏晨菲",
"Yanyan | 郑颖茵",
"Yvette | 孙若晗"
];

const G7C8 = [
"Aaron | 周建安",
"Alice | 彭馨怡",
"Amy | 梁康雅",
"Binbo | 林钊冰",
"Bobby | 杜晋鹏",
"Cassie | 吴诗媚",
"Cici | 余芊芊",
"Cindy | 杨婉煊",
"David | 刁家臻",
"Dong | 林博东",
"Eric Gan | 甘泽成",
"Eric Zhuo | 卓宇城",
"Ethan | 叶炫廷",
"Fred | 何沐宸",
"Hao Lin | 雷浩林",
"Havid | 刘振华",
"Horward | 蔡昊燃",
"Jack | 陈家和",
"Jerry | 刘家玮",
"Jia Yi | 黄嘉怡",
"Jolyne | 李嘉琳",
"Karry | 朱颂羽",
"Kerwin | 周建源",
"Lisa | 贺玉菡",
"Peter | 饶润辉",
"Romeo | 罗蜜欧",
"Sara | 卓栩如",
"Stephen | 谭宇昊",
"Steve | 曹开元",
"Susan | 涂依依",
"Void | 潘逸恒",
"Wendy | 李雯臻",
"Yentl | 郑颖彤",
"Yuki | 罗雅琪"
];

// Grade 6
const G6C2 = [
 "Tota         | 高子安 ",
 "Alex 1       | 黄浩然 ",
 "Alex 2       | 黄九皋 ",
 "Kelvin Li    | 黎辰予 ",
 "Gavin        | 李辅天 ",
 "Leo Li       | 李星爵 ",
 "Leo Liu 1    | 刘凯泽 ",
 "Torry        | 刘涛睿 ",
 "Leo Liu 2    | 刘廷诺 ",
 "Leo Liu 3    | 刘骁层 ",
 "Timi         | 刘祐均 ",
 "Jack         | 刘智豪 ",
 "Leon         | 卢羽腾 ",
 "Max          | 栾敬洲 ",
 "Martin       | 孟鼎淳 ",
 "Kelvin Pan   | 潘玉龙 ",
 "Xuchen       | 庞旭辰 ",
 "James        | 王镝云 ",
 "Reno         | 王焕然 ",
 "Lucas        | 吴思贤 ",
 "Clary        | 奚辰泽 ",
 "Henry        | 夏崇晖 ",
 "Kelvin Yi    | 伊浩铭 ",
 "Eric         | 张辰轩 ",
 "Yoyo         | 赵昱辰 ",
 "Will         | 朱熙然 ",
 "Sara         | 安珮瑄 ",
 "Kay          | 陈楚滢 ",
 "Emily        | 陈米莉 ",
 "Rita         | 陈子衿 ",
 "Linda        | 程子涵 ",
 "Amy Diao     | 刁爰元 ",
 "Diana        | 段玥如 ",
 "Amy He       | 何羿潼 ",
 "Nika         | 胡伊湄 ",
 "Dora         | 黄毓珺 ",
 "Jennifer     | 经姜毅 ",
 "Cindy        | 李昕畅 ",
 "Elena        | 梁馨文 ",
 "Grace        | 廖格曼 ",
 "Cherry       | 林昱汐 ",
 "Lucy         | 卢欣然 ",
 "Dianna       | 汤韵诗 ",
 "Cici         | 王雨馨 ",
 "Candy Wang   | 王涵   ",
 "Hermione     | 王铭暄 ",
 "Yoyo         | 吴辰   ",
 "Amy Wu       | 吴芊怡 ",
 "TT           | 夏宇彤 ",
 "Jessica      | 余瑾昕 ",
 "Candy Zhai   | 翟伟淇 ",
 "Jenny        | 张艺   ",
 "Kiwi         | 郑永欣 "
];

const G6C5 = [
"Beauty | 曾小桐",
"Cheyanne | 曾鑫悦",
"Matt | 曾致睿",
"Lucky | 程可  ",
"Sam | 陈冠燊",
"Kiki | 陈佳宁",
"Issac | 陈铭熙",
"Celine | 陈思灵",
"Claus | 陈炜康",
"Eric | 陈彦熹",
"Haley | 陈子谦",
"Kevin | 方健源",
"Louis | 冯钧泽",
"Eric | 高天佑",
"Hannah | 韩雨彤",
"Sean | 洪圣哲",
"Sissi | 洪思思",
"Gloria | 黄晨希",
"Pacino | 胡珀瑀",
"Thea | 胡歆予",
"Caroliine | 姜柄彤",
"Cassie | 江子涵",
"Gavin | 梁晋炜",
"Pierce | 梁宇轩",
"Cherry | 李辰睿",
"Sophie | 李佳忆",
"Emma | 李嘉怡",
"Ryan | 林嘉烨",
"Keki | 林柯岐",
"Gary | 刘嘉逸",
"Kevin | 刘宗恺",
"Luciana | 李音希",
"Jessica | 李知珏",
"Max | 李知珉",
"Niki | 龙澳南",
"Qiqi | 饶子锜",
"Ethan | 孙奕晨",
"Jass | 王领麓",
"Ethan | 王诗宇",
"Terry | 魏凡皓",
"Richard | 吴任頡",
"Mia | 吴锐淇",
"Carl | 许洺基",
"Kevin | 杨明昊",
"Elsa | 晏紫琦",
"Charles | 余镐澈",
"Ever | 余镐源",
"Flower | 余婉婷",
"Mcqueen | 余政羲",
"Vince | 郑浩嵩",
"Cindy | 郑家沁",
"Marcus | 郑新瀚"
]

const G6C6 = [
  "Tison |	蔡天舜",
  "Sherly |	陈诗妤",
  "Eason |	陈奕丞",
  "Jack |	郭涵旭",
  "Phoenix |	韩雨萌",
  "Thomas |	何依恒",
  "Alice |	贺诗婷",
  "Cici |	黄若嫣",
  "CC |	黄以晴",
  "Kelly |	金泳妍",
  "Jerry |	李承泽",
  "Dora |	李美辰",
  "Shann |	李尚恩",
  "Cindy |	李艳烨",
  "Joe |	李仲恩",
  "Coco |	李子涵",
  "Jason |	林泽锋",
  "Freda |	刘子妃",
  "Allan |	吕东霖",
  "Eric |	石皓文",
  "Sarah |	宋晨汐",
  "Jackey |	唐家瑞",
  "Abel |	汪庆祥",
  "Mila |	王米莱",
  "Wendy |	王雯迪",
  "Angela |	巫诗钰",
  "Coco |	熊媛可",
  "Kimi |	许峻华",
  "Bobby |	许钦涛",
  "Linda |	严灵玥",
  "Tracy |	尹希如",
  "Cody |	雍博然",
  "Cici |	余晨曦",
  "Adkins |	张铠泓",
  "Nina |	张莉旎",
  "Issac |	张诺一",
  "Angus |	赵天胤",
  "Jason |	赵星睿",
  "Feyman |	郑博颀",
  "Steven |	郑城熙",
  "Gary |	郑淏文",
  "Albert |	郑焱文",
  "Connor |	钟喆豪",
  "Dave |	周轩瑞",
  "Levie |	曾力为",
  "Jay |	曾铭祺",
  "Emma |	陈恩琦"
];

const G6C7 = [
 "Ryan         | 蔡昊霖 ",
 "Eason        | 陈伯勋 ",
 "Andrew       | 陈彦羲 ",
 "Linda        | 段玥如 ",
 "Ellen        | 冯馨阅 ",
 "Laura        | 冯羽彤 ",
 "Daniel       | 冯志博 ",
 "Dora         | 郭梓鑫 ",
 "Joe          | 洪承宙 ",
 "Colin        | 胡科名 ",
 "Cody         | 胡科扬 ",
 "Eva          | 胡舒文 ",
 "Bella        | 江怡娴 ",
 "Bobo         | 金浩轩 ",
 "Eric         | 靳鸿戈 ",
 "Jack         | 李泽霖 ",
 "Paul         | 刘弘毅 ",
 "Polin        | 全泊霖 ",
 "Rolin        | 沈若林 ",
 "William      | 涂建灏 ",
 "Eric         | 王君悦 ",
 "Alaiya       | 王文一 ",
 "Cindy        | 王暄   ",
 "Lusy         | 王语泽 ",
 "James        | 王子睿 ",
 "Susie        | 王梓宁 ",
 "Ryan         | 吴榕煦 ",
 "Wilson       | 吴奕臻 ",
 "Ivy          | 夏小涵 ",
 "Angela       | 谢予涵 ",
 "Harris      | 徐沣   ",
 "Maco         | 杨翰文 ",
 "Alina        | 杨荞语 ",
 "Adam         | 叶昊轩 ",
 "Jelly        | 于昕灵 ",
 "Candy        | 张沛健 ",
 "Amanda       | 张正伊 ",
 "Andy         | 郑熙麒 ",
 "Zoey         | 周乐儿 ",
 "Candy        | 周密   ",
 "Aimee        | 周昱妍 ",
 "Emma         | 叶子涵 ",
 "Harry        | 刘曙豪 ",
 "Wesley       | 伏钰汶 "
];

const G6C8 = [
 "Jimmy        | 边无际 ",
 "Sophie       | 曾子涵 ",
 "Mack         | 陈昊   ",
 "Vicky        | 陈慧琦 ",
 "Jackson      | 陈建维 ",
 "Edison       | 程宇墨 ",
 "Ivy          | 崔秋仪 ",
 "Summber      | 单凯洋 ",
 "Henry        | 方鸿睿 ",
 "Momo         | 胡瑾桐 ",
 "Robert       | 黄皓轩 ",
 "Ian          | 黄子恩 ",
 "Alvis        | 黄子渊 ",
 "Alia         | 金梓洋 ",
 "William      | 阚明哲 ",
 "Charlie      | 李佰阳 ",
 "Edward       | 李燊   ",
 "Amy          | 李炘芯 ",
 "Lisa         | 李梓菡 ",
 "Lynn         | 林诗诗 ",
 "Yancy        | 刘又瑄 ",
 "Lucy         | 彭予露 ",
 "Sally        | 苏婧秋 ",
 "Kene         | 万凯诺 ",
 "Chloe        | 文熙媛 ",
 "Daisy        | 肖舒窈 ",
 "Linda        | 肖雅灵 ",
 "Ken          | 姚煜坤 ",
 "Sisi         | 叶亦诗 ",
 "Celine       | 应明珍 ",
 "Coco         | 运彩儿 ",
 "Robin        | 周禄槟 ",
 "Carrie       | 周若晴 ",
 "Zoe          | 周梓墨 ",
 "Lucas        | 范宇卓 ",
 "Angela       | 黄莉媛 ",
 "Aden         | 林峻霆 ",
 "Chen         | 陈彦良 ",
 "Helen        | 王亦晗 ",
 "Ray          | 邓子锐 ",
 "Sunny        | 胡智涵 "
];
