//7G
const vocabSeven = [
    "person", 
    "cheerful", 
    "hard-working", 
    "patient", 
    "smart", 
    "probably", 
    "forget", 
    "smell", 
    "either", 
    "care", 
    "miss", 
    "joke", 
    "laugh", 
    "remain", 
    "strict", 
    "encourage", 
    "support", 
    "successful", 
    "member", 
    "paragraph",
    "take care of", 
    "tell jokes", 
    "make fun of", 
    "be strict about", 
    "give up", 
    "go to work", 
    "all day and all night", 
    "France", 
    "wine", 
    "tick", 
    "possible", 
    "Europe", 
    "store", 
    "vineyard", 
    "excellent", 
    "French", 
    "south", 
    "lie", 
    "coast", 
    "perfect", 
    "prefer", 
    "ski", 
    "tower", 
    "finish", 
    "lift", 
    "step", 
    "stairs", 
    "receiver", 
    "date", 
    "greeting", 
    "address", 
    "famous", 
    "department store", 
    "prefer to", 
    "go on holiday", 
    "go sightseeing",
    "blind", 
    "radio", 
    "programme", 
    "helpful", 
    "rescue", 
    "mean", 
    "receptionist", 
    "allow", 
    "pet", 
    "anywhere", 
    "apologize", 
    "lead", 
    "bark", 
    "wake", 
    "towel", 
    "bottom", 
    "finally", 
    "airport", 
    "appear", 
    "act", 
    "climb", 
    "dark", 
    "nothing", 
    "arrive at", 
    "by oneself", 
    "fall asleep", 
    "wake up", 
    "get down", 
    "fire engine", 
    "drop", 
    "journey", 
    "quantity", 
    "experiment", 
    "fresh", 
    "salt", 
    "voice", 
    "reservoir", 
    "add", 
    "chemical",
    "through", 
    "pipe", 
    "valuable", 
    "bit", 
    "bank", 
    "change", 
    "return", 
    "vapour", 
    "form", 
    "stir", 
    "continue",
    "crystal",
    "turn off",
    "add [sth] to [sth]",
    "a bit",
    "part of",
    "pocket money",
    "dry up",
    "electricity",
    "conversation",
    "identify",
    "rule",
    "anyone",
    "reply",
    "foolish",
    "wire",
    "connect",
    "cable",
    "moment",
    "battery",
    "cooker",
    "fridge",
    "bulb",
    "lock",
    "test",
    "tidy",
    "touch",
    "a packet of",
    "in a way",
    "connected to",
    "power station",
    "washing machine",
    "switch off",
    "tidy up",
    "air conditioner",
    "poem",
    "ordinary",
    "feeling",
    "order",
    "advice",
    "aloud",
    "group",
    "agree",
    "disagree",
    "rhyme",
    "complete",
    "well",
    "shower",
    "site",
    "narrow",
    "height",
    "superman",
    "seller",
    "smile",
    "rush",
    "crowd",
    "(not) at all",
    "worried about",
    "newspaper stand",
    "rush out",
    "a crowd of [sth]"
    "career",
    "planet",
    "satellite",
    "velvet",
    "diamond",
    "shoot",
    "host",
    "knowledge",
    "lively",
    "last",
    "actually",
    "anybody",
    "achieve",
    "sail",
    "decide",
    "train",
    "alone",
    "in the future",
    "used to go outside look like",
    "more and more",
    "grow up",
    "go sailing"
];

//6G
const vocabSix = [
    "scissors", 
    "tape", 
    "glue", 
    "tool", 
    "saw",
    "craftsman",
    "easily", 
    "still",
    "model house",
    "a long time ago",
    "at work",
    "long",
    "race", 
    "short race", 
    "win", 
    "long jump", 
    "high jump",
    "swimsuit",
    "swimming cap",
    "swimming pool",
    "warm-up",
    "fit",
    "swimming goggles",
    "weigh",
    "taller",
    "fantastic",
    "theatre",
    "go fishing",
    "get the crops in",
    "kilogram",
    "centimeter",
    "fan",
    "theater",
    "life",
    "writer",
    "computer",
    "broom",
    "drive",
    "poor",
    "wish",
    "carry",
    "photographer",
    "film",
    "digital",
    "sweep",
    "broom",
    "street sweeper",
    "wife",
    "fairy",
    "by hand",
    "right away",
    "in a short time",
    "oil",
    "brush",
    "paints",
    "artist",
    "unhappy ",
    "carefully",
    "street sweeper",
    "pen and paper",
    "street cleaner",
    "in the mountains",
    "under the sea",
    "in space",
    "online",
    "head teacher",
    "even",
    "dinosaur",
    "a piece of",
    "have a picnic",
    "better and better"
    "bell",
    "neck",
    "ago",
    "gatekeeper",
    "praise",
    "praise [sb] for [sth]"
    "sign",
    "middle",
    "special",
    "path",
    "may",
    "lost",
    "worry",
    "follow",
    "in the middle",
    "look out",
    "no smoking",
    "no swimming",
    "get lost",
    "some time",
    "on the way"
];

const storiesSix = [
    "\
  Brenda wants to have a picnic. She gets a basket. She puts sandwiches in the basket. The sandwiches are healthy. They are also tasty. She drives to the park. She lays out a blanket. She hears a sound. It is raining. She folds the blanket back. She puts the food in the basket.",
    "\
  Marco loves painting but he has no paints or even brushes. He uses a broom and ink to paint a dinosaur. A fairy sees his painting and says \"WOW! That dinosaur is so cool that I will give you a wish\". Marco wishes for real paints and brushes. Now he can add color to his dinosaur! Marco becomes a great painter."
];

const storiesSeven = [
    "\
  <strong>Helping a Billionaire</strong><br>\
  In a big city, there was a helpful receptionist named Lisa who worked in a famous department store for blind people, greeting customers with a warm smile. Lisa was patient with the customers and always helped them find what they needed. On her days off, she preferred to go sightseeing. One day, while out on her journey, Lisa saw a lost dog wandering the streets. She led the pet back to its owner, who was a billionaire. The billionaire pet owner gave Lisa $1,000 to say thank you.",
    "\
  <strong>How Bob Died:</strong><br><br> Once, in Paris, there was a cheerful person named Bob. Bob was hard-working and patient, but not very smart. He probably forgot things more than anyone else in the world. Bob started a vineyard in front of the Eiffel Tower because he loved the smell of grapes. All day and all night, tourists made fun of him for pretending to be a French wine expert. When he went to work in his \"vineyard\", he put water on the weeds and chemicals on the grapes (not smart). He thought the grapes would grow better if they were happy, so he did silly things like tell them jokes. And that's how Bob died: He skied down the Eiffel Tower to try to make the grapes happy.",
    "\
  The cheerful baker worked hard all night, forgetting the time. \"Hmm,\" he sniffed, \"does this bread smell like...wine?\" He shrugged, \"Probably not.\"  The next morning, his customers laughed!  His bread turned bright purple!",
];

function scrambleWord(word) {
    // Split the input word into an array of words
    const words = word.split(' ');

    // Scramble each word while preserving spaces
    const scrambledWords = words.map(word => {
	if (word.trim() !== '') {
	    // If the word is not empty after trimming spaces
	    // Convert the word into an array of characters
	    const characters = word.split('');
	    // Shuffle the characters
	    for (let i = characters.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[characters[i], characters[j]] = [characters[j], characters[i]];
	    }
	    // Join the characters back into a string
	    return characters.join('');
	} else {
	    // If the word is empty, return an empty string
	    return '';
	}
    });

    // Join the scrambled words array back into a string
    return scrambledWords.join(' ');
}

