#+TITLE: Grade 7 Test Results
#+AUTHOR:
#+STARTUP: inlineimages
#+EXPORT_FILE_NAME: Grade 7 Test Results
#+PROPERTY: HEADER-ARGS+ :eval no-export
#+OPTIONS: num: nil
#+SETUPFILE: ~/.config/emacs/setupfiles/readtheorg/readtheorg_inline.theme

* Test Design
I asked students to tell me about a story. If they could not provide a story, I provided a story for them. If they did not know any of the stories I gave (including stories they should know from our class), I asked them to tell me what they did yesterday. The goal was to test their ability to speak narratively, not to test their retention of story details. I finished by asking a couple of vocabulary questions from different units. If the story allowed it, I would ask the question with context, e.g., if the story is "A man went to a hotel," I could ask "Was the man blind? What animal do blind people usually have?"

** Grading
I designed the test so that at least the top 20% of the class would get an A++ and at least the next 20% would get A+. A student would not get a B without struggling in all aspects of the test, with a maximum score of 3/2/2.

*** Rubric
I graded the students with a maximum of five points for each of three skills: Understanding, speaking, and vocabulary. I weigh understanding higher than speaking and speaking higher than vocabulary. Roughly, two points of vocabulary is one point of speaking and two points of speaking is one point of understanding. So if a student was struggling in understanding and speaking, I tested them a little more on vocabulary to give them a chance at a better grade.

** Example Vocabulary Questions
Below are questions I would resort to if I could not test the vocabulary in the context of the story the student gave me (which was rare).

1. What is electricity? Where does it come from?
2. If you were blind, what animal would you like to be your eyes?
3. What is more valuable, dirt or crystals/jewels?
4. Would you prefer to dig a hole or build furniture? Which would make you dirtier?
5. Would you be happy if your mother made fun of you? Why?
6. Would you prefer to take the stairs or the lift? Is it harder or easier to take the stairs?

* Class 1
This class behaves very well and is always engaged in the lesson. Most students are at a good level of English, with only a few students who struggle significantly.
** A++
*** Yoo 王语杨 Wang Yuyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5       |
王语杨 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Aimee 刘妍汐 Liu Yanxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
刘妍汐 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Doris 李忆蓝 Li Yilan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

李忆蓝 has an advanced level of English. She understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum. She has reached an intermediate-high level of English and would benefit from reading native-level books in English.

She and 朱叶泉 are among the English speakers in the seventh grade. They also appear to be good friends and often chat in English, so I think that contributes to their high achievement in this sphere.

*** Angela 朱叶泉 Zhu Yequan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

朱叶泉 has an advanced level of English. She understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum. She has reached an intermediate-high level of English and would benefit from reading native-level books in English.

She and 李忆蓝 are among the English speakers in the seventh grade. They also appear to be good friends and often chat in English, so I think that contributes to their high achievement in this sphere.

*** Minnie 陈乐彤 Chen Letong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈乐彤 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Vincent 林琸潇 Lin GuZhao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
林琸潇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Jacky 刘浩然 Liu Haoran
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘浩然 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Marvin 马文畅 Ma Wenchang
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
马文畅 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Ivy 谢嘉洁 Xie Jiajie
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
谢嘉洁 had no trouble understanding me, spoke rather fluidly with precise pronunciation, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Jackle 乔荣康 Qiao Rongkang
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
乔荣康  had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Bailey 黄冬扬 Huang Dongyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄冬扬 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She realized how to properly answer a vocabulary question after we finished her test and before someone else had answered it in front of her, so I added the point back for her. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Cynthia 赵千陌 Zhao Qianmo
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
赵千陌 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. To test her vocabulary, I asked a question that, in retrospect, may be confusing. I said "was the ticket electric?" which I intended to be a nonsensical question, but she said "yes" because she understood my meaning to be "electronic" as the ticket was on a phone. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Raymond 刘睿泽 Liu Ruize
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘睿泽 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Steven 徐志宏 Xu Zhihong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
徐志宏 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Man 王艺渊 Wang Yiyuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王艺渊 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Bryant 陈子贤 Chen Zixian
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈子贤 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Guanzhen 李冠臻 Li Guanzhen
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
李冠臻 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.
*** Ivan 赵天羿 Zhao Tianyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
赵天羿 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kobe 张景治 Zhang Jingzhi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
张景治 jj had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

** A+
*** Kenny 王梓宣 Wang Zixuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
王梓宣 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Zina 黄琬淇 Huang Wanqi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
黄琬淇 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Monica 汪梓菡 Wang Zihan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
汪梓菡 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Alex 卓志俊 Zhuo Zhijun
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 3         |
卓志俊 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Paul 庞博 Pang Bo
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
庞博 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. He has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Miki 陈妙苒 Chen Miaoran
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
陈妙苒 had no trouble understanding me, and she spoke rather fluidly, but she forgot most vocabulary. She has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Haobang 郑皓帮 Zheng Haobang
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          4 |
郑皓帮 had no trouble understanding me, spoke with a consistent stammer, and remembered most vocabulary. He would benefit from graded readers more and aural practice.

*** Kenson 叶司瀚 Ye Sihan
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          4 |
叶司瀚 had no trouble understanding me and forgot some vocabulary. But I had some difficulty understanding him. When I listened to the recording, I realized he was saying "helped her" and "clever," but I did not understand "helped her" and I thought he had said "careful," so he needs some work on his pronunciation. He would benefit from aural practice and some phonics work.

** A
*** Ruihan 于睿涵 Yu Ruihan
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          3 |
于睿涵 had a little trouble understanding me, spoke with a consistent stammer, and forgot some vocabulary. He would benefit from more aural practice and graded readers.
*** Mona 刘思语 Liu Siyu
| Understanding | Speaking | Vocabulary |
|             3 |        5 |          2 |
刘思语 needed some help to understand me, but she was able to speak relatively well. She forgot most vocabulary. She would benefit from more aural practice and graded readers.

*** Jessica 方子嘉 Fang Zijia
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          4 |
方子嘉 had a little trouble understanding me with help, but much of the lack of understanding came from her nerves. I think she struggled to produce narrative English for the same reason because her pronunciation was very clear when she answered vocabulary questions, she simply couldn't string the words together properly. She would benefit from fluency exercises and graded readers.

*** Darren 熊彦彰 Xiong Yanzhang
| Understanding | Speaking | Vocabulary |
|             3 |        5 | 2         |
熊彦彰 had some trouble understanding me, even with help. He spoke clearly, but he forgot most vocabulary. He would benefit from more aural practice and some basic graded readers.

*** Anna 罗宇轩 Luo Yuxuan
| Understanding | Speaking | Vocabulary |
|             2 |        3 |          5 |
罗宇轩 had significant trouble understanding me, even with help and required translation. She struggled to produce narrative English. She remembered all vocabulary. She would benefit from remedial English and basic graded readers.

*** Simple 文兆轩 Wen Zhaoxuan
| Understanding | Speaking | Vocabulary |
|             3 |        2 |          4 |
文兆轩 is always joking and the class likes him for it. I cannot always tell when he does not understand me and when he is pretending not to understand me to be funny. He cannot produce narrative English and requires translation to understand, but he knew some of the vocabulary words I tested him on.

** B
*** Kitty 黄子仪 Huang Ziyi
| Understanding | Speaking | Vocabulary |
|             3 |        2 |          2 |
黄子仪 had significant trouble understanding me, even with help. She was not able to produce any narrative English and she forgot most vocabulary. She would benefit from  remedial English with lots of comprehensible input to help her catch up to the rest of the class.

*** Karan 陈可滢 Chen Keying
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          2 |
陈可滢 could not understand anything I said, even with help. She could not produce any output. The only thing she was able to say was her name and "rabbit," for "What animal do blind people have?" She was very nervous. She would benefit from very basic graded readers and some remedial English.

*** Eric 易佳豪 Yi Jiahao
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          2 |
易佳豪 struggles significantly with understanding me, even with help. He is not able to speak without resorting to Chinese. He forgot most vocabulary. He would benefit from remedial English with lots of comprehensible input to catch him up to the basics.

* Class 2
** A++
*** Rex 陈子逸 Chen Ziyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
陈子逸 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Dominic 陈梓越 Chen Ziyue
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈梓越 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Plastic Bag 冯沛欣 Feng Peixin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
冯沛欣 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Kenneth 华俊翔 Hua Junxiang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
华俊翔 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Siyi 黄思怡 Huang Siyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄思怡 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Nadia 黄玥涵 Huang Yuehan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄玥涵 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Lily 李紫芸 Li Ziyun
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李紫芸 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Tracy 柳宣如 Liu Xuanru
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
柳宣如 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Andrea 姚景暄 Yao Jingxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
姚景暄 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Ricky 肖嘉轩 Xiao Jiaxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

肖嘉轩 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kimi 杨航 Yang Hang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
杨航 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Xinxin 张馨心 Zhang Xinxin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
张馨心 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Betty 钟恩乐 Cheng Enle
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
钟恩乐 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Sam 赵烽棋 Zhao Fengqi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
赵烽棋 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

** A+
*** Roy 刘偌希 Liu Ruoxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
刘偌希 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. He would benefit from graded readers.

*** Win 黎致蓥 Li Chiying
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |
黎致蓥 had no trouble understanding me, and spoke accurately with a stammer, and remembered most vocabulary. He would benefit from reading graded readers.

*** Lydia 常宸菲 Chang Chenfei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |  4         |
常宸菲 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She would benefit from graded readers.

*** Ocean 邓博涵 Deng Bohan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
邓博涵 had no trouble understanding me, and spoke accurately with a stammer, and remembered most vocabulary. He would benefit from reading graded readers.

*** Yuyan 郁言 Yuyan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
郁言 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Bella 邢可佳 Xing Kejia
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 3         |
邢可佳 had no trouble understanding me, spoke rather fluidly, and forgot some vocabulary. She has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Eloise 杜林萱 Du Linxuan
| Understanding | Speaking | Vocabulary |
|             5 |        4 | 5         |
杜林萱 had no trouble understanding me, and spoke accurately with a stammer, and remembered most vocabulary. She would benefit from reading graded readers.

*** Baby 董怀恩 Dong Huaien
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          4 |
董怀恩 had no trouble understanding me, and spoke accurately with a stammer, and remembered most vocabulary. She would benefit from reading graded readers.

** A
*** Kim 许嘉轩 Xu Jiaxuan
| Understanding | Speaking | Vocabulary |
|             5 |        3 | 4         |
许嘉轩 had no trouble understanding me, but struggled a lot to produce much English, so he may be coming out of a silent period, and remembered all vocabulary. He would benefit from graded readers.

*** Jason 尹家兴 Yin Jiaxing
| Understanding | Speaking | Vocabulary |
|             4 |        4 | 5        |
尹家兴 had a little trouble understanding me, spoke rather timidly but clearly, and remembered all vocabulary. He would benefit from more aural practice and graded readers.

*** Mandy 蔡馥蔓 Cai Fuman
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          4 |
蔡馥蔓 understood me with a little help and was able, somewhat, to speak. She forgot some vocabulary. She would benefit from graded readers.

*** Max 马煜轩 Ma Yuxuan
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          5 |
His lack of understanding stems mostly from his lack of vocabulary. He seems to understand the "flow" of English relatively well, but he needs a lot more comprehensible input.

*** Ben 孙嘉沐 Sun Jiamu
| Understanding | Speaking | Vocabulary |
|             4 |        4 | 3         |
孙嘉沐 could not produce much English without resorting to Chinese, but he seemed to understand me for the most part. He forgot some vocabulary words. He would benefit from some remedial English and comprehensible input with more aural practice.

*** Jenny 李佳霓 Li Jiani
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          3 |
李佳霓 required some help to understand me and I had some difficulty understanding her. She forgot most vocabulary, but she was able to pull through. She would benefit from some remedial English and more aural practice with lots of comprehensible input to catch up.

*** Taihe 吴泰和 Wu Taihe
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          2 |
吴泰和 could not produce much English without resorting to Chinese, but he seemed to understand me for the most part. He forgot most vocabulary words. He would benefit from some remedial English and comprehensible input with more aural practice.

*** Emily 冯子逸 Feng Ziyi
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          2 |
冯子逸 required some help to understand me and I had some difficulty understanding her. She forgot most vocabulary, but she was able to pull through. She would benefit from some remedial English and more aural practice with lots of comprehensible input to catch up.

*** David 邓佳洪 Deng Jiahong
| Understanding | Speaking | Vocabulary |
|             3 |        2 |          5 |
邓佳洪 remembered the vocabulary words, but struggled to understand me when I spoke to him and he could not produce English sentences. I think, therefore, he is in his silence period and would benefit from basic comprehensible input and more aural practice.

*** Lulu 张璐 Zhang Lu
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          4 |
张璐 struggles to understand me without some help. She also cannot do narrative speech in English at this time. She may be in her silent period. She would benefit from more aural practice and graded readers to build her confidence.

*** Yingqian 叶颖谦 Ye Yingqian
| Understanding | Speaking | Vocabulary |
|             3 |        3 | 3         |
叶颖谦 struggles to understand me, but some of the struggle is theatre he puts on for other kids as the class clown. He wants to make them laugh, and he usually succeeds, so he is pretty funny. He resorted to Chinese a lot when talking to me. I made him restart the test a couple of times to make him prepare for it while I tested the other students. After he had a story fresh in his mind, he did much better. He would benefit from quiet reading time without distractions with graded readers.
*** Eddy 刘奕潇 Liu Yixiao
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          3 |
刘奕潇 had some trouble understanding me. He could not produce narrative English for me, and he struggled with the vocabulary. He would benefit from some remedial English with lots of basic comprehensible input.

*** Wenkang 张文康 Zhang Wenkang
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          3 |
张文康 had some trouble understanding me. He could not produce narrative English for me, and he struggled with the vocabulary. He would benefit from some remedial English with lots of basic comprehensible input.

*** Daniel 甘培煜 Gan Peiyu
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          2 |
甘培煜 required some help to understand me and I had difficulty understanding him. He forgot most vocabulary, but he was able to pull through. He would benefit from some remedial English and more aural practice with lots of comprehensible input to catch up.

* Class 3
This class has stellar English. Nobody performed lower than A+.
** A++
*** Claire 陈奕臻 Chen Yizhen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

陈奕臻 is a joy to have in class. She understands all material I tested and spoke rather fluidly despite being visibly nervous. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.
*** Jeffrey  潘知远 Pan Zhiyuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
潘知远 understands all material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Xiao     肖睿轩 Xiao Ruixuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
肖睿轩 understands all material I tested and spoke rather timidly with a small stammer. He would benefit from graded readers and fluency exercises.

*** Chong    许嘉翀 Xu Jiachong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
许嘉翀 understands all material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.


*** Daisy    叶岱灵 Ye Dailing
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

叶岱灵 understands all material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Qi 傅畦之 Fu Qizhi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

傅畦之 understands all material I tested and spoke rather fluidly. I get the impression sometimes that he pretends his English is not very good for his friends in class, but it is above average. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Evia 张涵伊 Zhang Hanyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
张涵伊 understands all material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Billy 张润瑄 Zhang Runxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
张润瑄 understands all material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Angelia 郑可心 Zheng Kexin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

郑可心 understands all material I tested but spoke with a small stammer. She almost forgot some vocabulary, but it came to her at the last second. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Jack 周裕洋 Zhou Yuyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

周裕洋 understands all material I tested but spoke with a small stammer. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Leslie 邓禹乐 Deng Yule
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
邓禹乐 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Yolanda 董培渝 Dong Peiyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
董培渝 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Rain 杜雨洋 Du Yuyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
杜雨洋 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Bruce 范奕昊 Fan Yihao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
范奕昊 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Fiona 范语菲 Fan Yufei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
范语菲's English is at a native level. I have nothing to improve on in the context of this class. To improve her English beyond its current level, I would recommend academic practice, e.g., reading and writing about history or science.

Side note: She told me about the Hunger Games and said "but they spell capitol with an 'o' instead of an 'a'" and I did not have time to tell her that they do that because "capitol" means "on top of a hill," and the reason The Capitol is spelled with an 'o' in the Hunger Games is because it takes place in a post-apocalyptic United States and the government buildings in Washington D.C. are in a place we call "Capitol Hill." So, "the Capitol" is the place where the goverment of the United States sits inside of "the capital," Washington D.C., the city where "the capitol" is.

*** Tiger 郭柏城 Guo Baicheng
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
郭柏城 had no trouble understanding me, spoke rather fluidly, stammering only slightly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Hannah 郭梓涵 Guo Zihan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
郭梓涵 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Ceiling 洪浠琳 Hong Xilin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
洪浠琳 had only a little trouble understanding me (when I said "who is the bad guy in Harry Potter" she said "Ron," which is Harry Potter's best friend, but that was the only mistake in understanding), but she spoke rather fluidly and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Chloe 胡馨睿 Hu Xinrui
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
胡馨睿 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Jenny 黄恋茹 Huang Lianru
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄恋茹 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Daniel 黄应中 Huang Yingzhong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄应中 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Oscar 黄梓洋 Huang Ziyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄梓洋 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kai 霍恩恺 Huo Enkai
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
霍恩恺 had no trouble understanding me, spoke rather fluidly, though it was clear to me he was sticking to very basic language to seem more fluent (which is totally fine), and remembered all vocabulary. He would benefit from graded readers to deepen his langauge.

*** Edison 蓝野 Lan Ye
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
蓝野 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Janice 李嘉荷 Li Jiahe
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李嘉荷 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary.

*** Kelly 李雨函 Li Yuhan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李雨函 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Hang 李雨航 Li Yuhang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李雨航 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Yu 刘广宇 Liu Guangyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘广宇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Daniel 刘倬恺 Liu Zhuokai
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘倬恺 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kevin 罗凯辰 Luo Kaichen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
罗凯辰 had no trouble understanding me, even when I left the curriculum, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Sissi 毛语熙 Mao Yuxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
毛语熙 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

** A+
*** Venus    温芷懿 Wen Zhiyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

温芷懿 understands all material I tested and spoke rather fluidly. She misspoke on some vocabulary, but in a way that still makes sense, so I took only one point. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Emily 叶馨彤 Ye Xintong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

叶馨彤  understands all material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Lily 周子熙 Zhou Zixi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

周子熙 understands all material I tested but spoke with a small stammer. She had memorized a story before the test, so I had to stop her to ask some other questions to see her speaking (rather than reciting) skill. She has reached an intermediate level of English and would benefit from fluency exercises to build her confidence (so next time she won't think she has to memorize a story for the test).

*** Caesar 蔡熙 Cai Xi
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 4         |
蔡熙 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary, and when I tried to correct him on it, he adequately defended his position:

- "Was the boy selfish or generous?"
- "Generous."
- "Are you sure? What does selfish mean?"
- "Oh. Yes. He gave her love."

The boy gave her nothing material in the story, but you can argue he gave her love.

He would benefit from graded readers.

*** Cici 曾乐儿 Zeng Leer
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
曾乐儿 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary except one word, "electricity." She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Renee 李雨璇 Li Yuxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
李雨璇 had no trouble understanding me, even when I left the curriculum, spoke rather fluidly, and remembered all vocabulary except "valuable," but she understood everything around it and would surely have answered correctly with more context around the term. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Andy 魏子愚 Wei Ziyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
魏子愚 understands most material I tested and spoke rather fluidly, but he forgot some vocabulary. He has reached an intermediate level of English and would benefit from graded readers.

* Class 4
** A++
*** Kenny 钟睿邦 Zhong Ruibang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
钟睿邦 is always excited and willing to speak in class. He has no trouble understanding me and speaks with few stammers. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.
*** Teresa    邓丽慈 Deng Lici
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
邓丽慈 had no trouble understanding me, was able to speak clearly (with a small stammer and minor grammar errors), and remembered all vocabulary. She was very nervous and felt like she needed a written reference, but when I let her use the reference, took it away, and asked questions about it, she was able to answer everything from the reference perfectly, so her English is better than she thinks it is. She would benefit from graded readers.

*** Jessica 曹婉宁 Cao Wanning
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
曹婉宁 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She was able to answer what some vocabulary terms mean using correct English, which shows a good level of circumlocution as well. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Mia 曾茗   Zeng Ming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
曾茗 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Sofia    张舒涵 Zhang Shuhan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

张舒涵 had only a tiny bit of trouble understanding me, which seemed to come from nerves because she still answered very quickly and fluidly, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers and/or native-level English literature.

*** Paddy 严伟哲 Yan Weizhe
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

严伟哲 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Coco 饶子滢 Rao Ziying
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

饶子滢 had no trouble understanding me or most of the material I tested and spoke rather fluidly. She underestimates her English skill and is disproportionately nervous. She has reached an intermediate level of English and would benefit from graded readers or native-level English literature. She may also get a particular benefit from more aural practice to build her confidence, so she can "know what she knows."

*** Elsie 温烨馨 Wen Yexin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

温烨馨 had no trouble understanding me or most of the material I tested but stammered often. She would benefit from more aural practice and graded readers.

*** Sam 郭旭晨 Guo Xuchen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

郭旭晨 had no trouble understanding me or most of the material I tested but stammered occasionally. He also used vocabulary without my prompting. He has reached an intermediate level of English and would benefit from graded readers or native-level English literature.

*** Annie    邹和桉 Zou Hean
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
邹和桉 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She told me she is sad about her bad exam in English, but she seems on track from our oral conversation. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Alex Wu 吴煜哲 Wu Yuzhe
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
吴煜哲 had no trouble understanding me and speaks fluidly. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Alex Guo 郭佩鑫 Guo Peixin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
郭佩鑫  had no trouble understanding me and speaks fluidly. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Caroline 陈妤越 Chen Yuyue
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈妤越 had no trouble understanding me or the material I tested and spoke relatively fluidly. She would benefit from graded readers or native-level English literature.

*** Hugo 郑汶昊 Zheng Wenhao
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
郑汶昊 had no trouble understanding me or the material I tested and spoke with only a few stammers. He would benefit from graded readers.

*** Andy Zheng 郑智华 Zheng Zhihua
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

郑智华 had no trouble understanding me or the material I tested and spoke with only a few stammers. He has reached an intermediate level of English and would benefit from graded readers or native-level English literature.

*** Stephen 董博文 Dong Bowen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

董博文 had no trouble understanding me or the material I tested and spoke with only a few stammers. He has reached an intermediate level of English and would benefit from graded readers or native-level English literature.

*** Nico 李怡乐 Li Yile
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

李怡乐 had no trouble understanding me or the material I tested and spoke with only a few stammers. He would benefit from graded readers.

*** Alice 邹沅芷 Zou Yuanzhi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

邹沅芷 had no trouble understanding me or the material I tested and spoke with only a few stammers. She may have reached an intermediate level of English and would benefit from graded readers or native-level English literature.

** A+
*** Andy Ma 马铭俊 Ma Mingjun
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

马铭俊 had no trouble understanding me or most of the material I tested but stammered often. He would benefit from more aural practice and graded readers.

*** Elsa 马怡然 Ma Yiran
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
马怡然 has a little trouble understanding me and speaks very timidly with a few stammers, but not enough to impact her score. She would benefit from graded readers and aural practice.

*** William Wen 文俊哲 Wen Junzhe
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |
文俊哲 had no trouble understanding me, spoke rather fluidly but had to resort to Chinese on occasion, which indicates that he needs to practice circumlocution. He remembered all vocabulary. He would benefit from graded readers.

*** Leo       淦子邀 Gan Ziyao
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |
淦子邀 had no trouble understanding me, spoke well but resorted to Chinese occasionally and got help from his friends, and remembered all vocabulary. He would benefit from graded readers.

*** William Wang 汪敏皓 Wang Minhao
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |

汪敏皓 had no trouble understanding me but did need to resort to Chinese for some output. Vocabulary retention seemed good, but there were students nearby shouting the answers, so I could not be sure how much he remembered and how much he got from them. He would benefit from graded readers.

*** Nick 朱家尧 Zhu Jiayao
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          5 |
朱家尧 had only a little trouble understanding me, spoke rather fluidly, and remembered all vocabulary. I asked "if you are blind, what can you not do?" and he said "dog" because, I think, he had heard me ask another student what animal blind people may have. But when I repeated, the question, he (mostly) correctly said "look." He would benefit from graded readers.

*** Abby     智语轩 Zhiyuxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
智语轩 had very little trouble understanding me, spoke rather fluidly, and remembered all vocabulary with a little help. She was nervous so she relied somewhat on help from her friends, but she could have done well without them too. She would benefit from graded readers.

*** Hulk 陈梓浩 Chen Zihao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |

陈梓浩 had no trouble understanding me, spoke rather fluidly, but could not remember most vocabulary. This indicates to me that he does not learn well from vocabulary lists and would benefit more from learning words in context with something like free voluntary reading and graded readers.

*** Tom 林华涛 Lin Huatao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

林华涛 had no trouble understanding me except when I went outside the curriculum, spoke rather fluidly, and remembered most of the  vocabulary.

*** Lily 梁紫欣 Liang Zixin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
梁紫欣 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers.

** A
*** Ada 陈嘉璇 Chen Jiaxuan
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          3 |
陈嘉璇 had a little trouble understanding me without some help. She stammers as she speaks, but her output is correct. She forgot some of the vocabulary without context. She would benefit from more aural practice and fluency exercises.

*** Lemon 游柠璐 You Ninglu
| Understanding | Speaking | Vocabulary |
|             3 |        3 | 4         |
游柠璐 had trouble understanding me without help. He also resorted to Chinese often during the exam and I had some difficulty understanding his English. He forgot some of the vocabulary without context. He would benefit from more aural practice and fluency exercises and maybe some basic graded readers.

*** Camellia 王紫萱 Wang Zixuan
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          3 |
王紫萱 had some with trouble understanding me without help and with producing output without a reference card, but she was able to do it in the end. She forgot some vocabulary. She would benefit from graded readers and aural practice.

*** Billy 刘昊霆 Liu Haoting
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          3 |
刘昊霆 had a little trouble understanding me, but understood with help and stammered while speaking. He would benefit from graded readers and more aural practice.

*** Amy 罗宇泓 Luo Yuhong
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          2 |
罗宇泓 struggles significantly with understanding me and with producing output, even with help. After she could not produce any output, told her to re-read the story of the blind man and the dog and then, when I asked her to do the test again, she still did not know about it the story or what "blind" meant. She would benefit from remedial English and basic graded readers.

*** John A.K.A. "Turtle" 曾瑞   Zeng Rui
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          5 |

曾瑞 struggled to understand me, even with some help, but he spoke relatively fluidly and knew all of the material I tested. He would benefit from graded readers and fluency exercises.

*** Kevin 吴卓毅 Wu Zhuoyi
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          2 |
吴卓毅 had trouble understanding me without translation. He could not produce a full English sentence and he could not remember any vocabulary tested. He would benefit from remedial English and lots of comprehensible input; maybe some very basic graded readers.

* Class 5
This class is very competitive and vocal about it. They love the Exploding Kittens game, so we play it often.

** A++
*** Kiki 黄灵熙 Huang Lingxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄灵熙	had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Annie 黄梓宁 Huang Zining
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
黄梓宁 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Amy 李妍兮 Li Yanxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李妍兮 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Katherine 王瀚淇 Wang Hanqi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王瀚淇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Paul 王梓铭 Wang Ziming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王梓铭 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Rachel 王梓睿 Wang Zirui
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王梓睿 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Mingming 赵子铭 Zhao Ziming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
赵子铭 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature. She did not get 100% on her vocabulary, but she demanded to do it again, and I gave her all of the vocabulary questions and she aced it. Her English is quite good.

*** Doreen 张雅轩	Zhang Yaxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
张雅轩 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kimi 占云逸	Zhan Yunyi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
占云逸 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Yuki     梁钰淇 Liang Yuqi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
梁钰淇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Jack 叶梓铭	Ye Ziming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
叶梓铭 had a no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

** A+
*** Kenneth   洪义康 Hong Yikang
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |
洪义康 understands all of the material I tested and had no trouble understanding me. I had some trouble understanding some of what he said, so I took a point from Speaking. He would benefit from aural practice to improve his pattern recognition for English.

*** Pear 肖瑞雅 Xiao Ruiya
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
肖瑞雅 understands most of the material I tested and had only a little trouble understanding me. She missed some vocabulary but didn't struggle for the most part. She would benefit from consuming graded readers and aural practice.

*** Aemy 刘依诺 Liu Yinuo
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 4         |

刘依诺 misremembered many details about the story we were talking about, but her production of the English in that misremembering was on point, which I found kind of funny. She understands most of the material I tested and had no trouble understanding me except when I went outside the curriculum. She would benefit from consuming graded readers and aural practice.

*** Terb 方品涵 Fang Pinhan
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 4         |
方品涵 understands most of the material I tested and had no trouble understanding me even when I went outside the curriculum. He misspoke a couple of times, but not in a major way (once saying "born" instead of "broken"). He missed some vocabulary but didn't struggle for the most part. He would benefit from consuming graded readers and aural practice.

*** Aimee 罗亦葭 Luo Yijia
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
罗亦葭 understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum. She struggles a bit in speaking while trying to remember the words she wants to use or how to say the sentence she wants to say. She would benefit from consuming graded readers and aural practice.

*** Vicky 林语津 Lin Yujin
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 4         |
林语津 had no trouble understanding me. She stammered a bit when she was speaking, but she was able to fully articulate her ideas, with some small grammar mistakes. She is close to an intermediate level and would benefit from graded readers.

*** Abby 简竹君 Jian Zhujun
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
简竹君 had little trouble understanding me, spoke rather fluidly, and remembered most of the vocabulary. She would benefit from graded readers and more aural practice.

*** Ricky 袁瑞泽 Yuan Ruize
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 3         |
袁瑞泽 had only a little trouble understanding me, but he spoke rather fluidly, and remembered most vocabulary. He would benefit from graded readers.

*** Amy 张欣怡 Zhang Xinyi
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |

张欣怡  has good English but she second-guesses herself and stammers because she is passing what she wants to say through a filter of grammar and vocabulary. I think what she needs is to read graded readers to develop her confidence.
*** Angela 刘芷萌 Liu Zhimeng
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          3 |
刘芷萌 had no trouble understanding me, spoke rather fluidly but resorted to Chinese to explain time travel because she was floundering about it in English (understandable), and forgot most of the vocabulary I tested. She would benefit from graded readers.

*** Jerry 高逸明 Gao Yiming
| Understanding | Speaking | Vocabulary |
|             5 |        4 | 3         |

高逸明 understands most of the material I tested and had no trouble understanding me even when I went outside the curriculum. He struggles a bit in speaking and says his English is bad, but I think he just needs to build his confidence because I had very little trouble following him. He was not able to remember much of the vocabulary, so he does not appear to learn vocabulary from a list very well and would benefit from learning words in context rather than out of context. He would benefit from consuming graded readers and aural practice.

*** Linda 李梓涵 Li Zihan
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          3 |

李梓涵 had a little trouble understanding me, but most of her trouble came in producing output. She was very nervous. She would benefit from more comprehensible input and fluency exercises to build her confidence.

*** Corry 徐哲宁 Xu Zhening
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          4 |
徐哲宁 had some trouble understanding me. He stammers often and I sometimes did not understand him, but he managed to pull through. He would benefit from graded readers.

*** Simon 尹曦禾 Yin Xihe
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          3 |
尹曦禾 had only a little trouble understanding me, but he struggled to produce much output and did so rather timidly, and forgot some vocabulary. He would benefit from more aural practice, fluency exercises, and some graded readers.

*** Ethan 张竣轶 Zhang Junyi
| Understanding | Speaking | Vocabulary |
|             4 |        5 | 2         |
张竣轶 had a little trouble understanding me, and he stammered very often, though I understood everything, but he forgot most vocabulary. He would benefit from graded readers and fluency exercises.

*** Andy 刘子轩 Liu Zixuan
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          3 |
刘子轩 had a little trouble understanding me, spoke rather fluidly but resorted to Chinese occasionally. He struggled with some of the vocabulary, but he got there in the end. He would benefit from graded readers.

** A
*** Jane 文心琪 Wen Xinqi
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          2 |

文心琪 understood me most of the time, but she required some help. She was not able to correctly use some vocabulary. She struggles a bit in speaking while trying to remember the words she wants to use or how to say the sentence she wants to say. She would benefit from more aural practice.

*** Jim 王昱超 Wang Yuchao
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          2 |

王昱超 struggles to understand me significantly and I struggled to understand him at times, but he is very good at circumlocution and he speaks relatively confidently. The only time he was stumped from not knowing a word while talking was when he tried to tell me about a "straw house" from the Three Little Pigs. He did not know any of the vocabulary words, but he tried. He did not know what "France" means, but this class had a unit where a whole section early on was dedicated to tourism in France, so he might have been struggling to understand from the beginning of this semester.

*** Eric Fu   富雨轩 Fu Yu Xuan
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          3 |

富雨轩 had some trouble understanding some of the material I tested, but he could follow me with some help. I was not able to understand everything he said. When he was saying "wolf," I thought he was saying "awful" because he adds a schwa to the end of words that end in 'f.' He would benefit from more aural practice for his understanding and oral practice to work on his phonics.

*** Yuhao 梁钰浩 Liang Yuhao
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          2 |
梁钰浩 had some trouble understanding me. I also had some trouble understanding him and he needed to resort to Chinese occasionally, though he did speak somewhat fluidly despite a consistent stammer. He would benefit from more aural practice and fluency exercises to improve his phonics and understanding.

*** Ocean 尹子龙 Yin Zilong
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          2 |
尹子龙 had trouble understanding me, and he could not speak without resorting to Chinese. He also could not remember most vocabulary I tested. He would benefit from some remedial English, some basic graded readers, and more aural practice.

*** Cindy 张昕曈 Zhang Xintong
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          4 |
张昕曈 had some trouble understanding me even with help, struggled to speak narratively, and remembered most vocabulary. She would benefit from basic graded readers and more aural practice.
** B
*** Irene 丘若霖 Qiu Ruolin
| Understanding | Speaking | Vocabulary |
|             2 |        3 | 2         |

丘若霖 struggled to understand what I said even with help and could not produce any English beyond very basic things like "how are you?" and "no". I think a lot of her lack of production comes from anxiety. She would benefit from remedial English and lots of comprehensible input; maybe some very basic graded readers.

*** Eric Guo  郭昊明 Guo Haoming
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          2 |

郭昊明 He did not speak at all.

It seems he could not understand almost anything I said and did not speak any words other than "monkey." He didn't know any of the vocabulary words I tried to test him on. He was also very nervous, and I think that impacted his performance. We need to build his confidence to improve his English, and the only way to do that is to help him master the basics. Some of his classmates are well ahead of him, so I think he may feel left behind and might have given up on English already. I recommend remedial English for him so he can catch up with the basics.

* Class 6
** A++
*** Felix 汤济成 Tang Jicheng
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
汤济成 is among the best English speakers in the seventh grade. He understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum. His pronunciation is impeccable. He has reached an intermediate-high level of English and would benefit from reading native-level books in English.

*** Jason 余卓朗 Yu Zhuolang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
余卓朗 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.
*** Aven 陈煜希 Chen Yuxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈煜希 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Elaine 柯以贤 Ke Yixian
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

柯以贤 understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum, but she stammers when producing output, so she would benefit from fluency exercises.

*** Hubert 陈伟杰 Chen Weijie
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

陈伟杰 understands all of the material I tested and had no trouble understanding me even when I went outside the curriculum, but he did stammer somewhat when producing output, so he would benefit from fluency exercises. He has reached an intermediate level of English.

*** Helen 邓禾   Deng He
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

邓禾 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kevin 李树豪 Li Shuhao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

李树豪 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Amy 盛思书 Sheng Sishu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
盛思书 had no trouble understanding me. She stammered as she spoke, but she spoke clearly. She remembered all vocabulary. She has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Isla 崔禾瑾 Cui Hejin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
崔禾瑾 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Doris 杨子萱 Yang Zixuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5          |
杨子萱 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary, even when I left the curriculum. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Jimmy 王天穗 Wang Tiansui
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王天穗 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary words. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Marry 朱璇   Zhu Xuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
朱璇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Yiming 陈奕鸣 Chen Yiming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈奕鸣 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers.

*** Ray      宋睿轩 Song Ruixuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈奕鸣 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Joy       蔡宇熙 Cai Yuxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
蔡宇熙 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers.

*** Max      杨煜熙 Yang Yuxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
杨煜熙 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Timmy    廖泓宇 Liao Hongyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
廖泓宇 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Yoyo 沈灿辰 Shen Canchen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
沈灿辰 had no trouble understanding me, spoke rather fluidly with few stammers, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Zimo 冉子墨 Ran Zimo
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5          |
冉子墨 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Jemimah 胡慧心 Hu Huixin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
胡慧心 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Isabella 周永昕 Zhou Yongxin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

周永昕 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She would benefit from graded readers.

*** Leon 周子渝 Zhou Ziyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
周子渝 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Vincent  王浩鑫 Wang Haoxin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王浩鑫 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

** A+
*** Susie 郑舒兮 Zheng Shuxi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
郑舒兮 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She would benefit from graded readers.


*** Ethan 李嘉巍 Li Jiawei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

李嘉巍 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. He has almost reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Mora 王炎舒 Wang Yanshu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
王炎舒 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She would benefit from graded readers.

*** Larry 王子乐 Wang Zi Le
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
王子乐 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. He would benefit from graded readers.

*** Brian    杨博睿 Yang Borui
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
杨博睿 had no trouble understanding me, spoke somewhat fluidly despite using Chinese to tell me he didn't know vocabulary words. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Hyman 洪浩铭 Hong Haoming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |
洪浩铭 had no trouble understanding me. He spoke rather fluidly, but he resorted to Chinese occasionally and forgot some vocabulary. He would benefit from graded readers.
*** Ryan 赵惊远 Zhao Jingyuan
| Understanding | Speaking | Vocabulary |
|             5 |        4 | 5          |

赵惊远  had no trouble understanding me. He spoke very timidly, and it was sometimes hard to understand him. He remembered all vocabulary words. He would benefit from graded readers and more aural practice.

*** Alysa 李晓桐 Li Xiaotong
| Understanding | Speaking | Vocabulary |
|             5 |        3 |          5 |
李晓桐 was very nervous and could not produce almost any output, but it was obvious she mostly understood me. She would benefit from more aural practice and graded readers to build her confidence in English.

*** Coco 李米   Li Mi
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          5 |

李米 understands all of the material I tested and had only a little trouble understanding me (I was telling her she could stop telling the story because we needed to test other things, but she just kept telling the story). She made only minor grammar errors, and only on structures that are outside of the curriculum, so she did a good job there as well. She would benefit from more aural practice and graded readers.

*** Tommy 崔添铭 Cui Tianming
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          5 |

崔添铭 had a little trouble understanding me with help, spoke clearly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

** A
*** Ellie 马兴蕾 Ma Xinglei
| Understanding | Speaking | Vocabulary |
|             4 |        5 | 4         |
马兴蕾 had some trouble understanding me. She spoke very timidly and with few mistakes. She remembered most vocabulary words. She would benefit from graded readers and more aural practice.


*** Annie 莫谨榕 Mo Jinrong
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          5 |
莫谨榕 had some trouble understanding me. She spoke very timidly and with few mistakes. She remembered all vocabulary words. She would benefit from graded readers and more aural practice.

*** Hendy 赵启恒 Zhao Qiheng
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          5 |
赵启恒 had some trouble understanding me. He spoke fluidly when he spoke, but he resorted to Chinese to say basic things like "I don't know." He remembered all vocabulary words. He would benefit from graded readers and more aural practice.

*** Tony 肖泓宇 Xiao Hongyu
| Understanding | Speaking | Vocabulary |
|             3 |        4 | 4         |
肖泓宇 had some trouble understanding me, even with help. I sometimes did not understand what he said, but he remembered most vocabulary words. He would benefit from more comprehensible input and aural practice.

* Class 7
The bell curve skews to the right in this class, so most students have pretty good English, and even the students with lower scores had passable English.
** A++
*** Hoshi    李雅妍 Li Yayan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李雅妍 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.
*** Alan     石展嘉 Shi Zhanjia
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
石展嘉 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Tiger     陈禹廷 Chen Yuting
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈禹廷 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Allen 曾浚朗 Zeng Junlang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
曾浚朗 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Bell      陈煜豪 Chen Yuhao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈煜豪 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He would benefit from reading graded readers or native-level English literature.

*** Cosmo     郭子墨 Guo Zimo
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
郭子墨 had no trouble understanding me besides on one question where his answer made sense in a way that I know he just misheard me ("What animal would you have if you were blind" "Blind? Can't see? Bat."), spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature. bat for blind question

*** Candice  李嘉桐 Li Jiatong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
李嘉桐 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She would benefit from reading graded readers.

*** Laura 刘芷玥 Liu Zhiyue
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘芷玥 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She volunteered to tell me about a Jane Austen book, Pride and Prejudice. Her love of English is clear, and she's always quiet in class. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Linda    林子晗 Lin Zihan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
林子晗 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Andy     刘浩涵 Liu Haohan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
刘浩涵 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He would benefit from reading graded readers or native-level English literature.

*** Usi      苏晨菲 Su Chenfei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
苏晨菲 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Yvette   孙若晗 Sun Ruohan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
孙若晗 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature. She told me about Harry Potter, so she may already be reading native-level English.

*** Marcus   王彦瑜 Wang Yanyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
王彦瑜 had no trouble understanding me or any of the material I tested and spoke with a consistent stammer. He would benefit from reading graded readers or native-level English literature.

*** Bella    王子墨 Wang Zimo
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
王子墨 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Jason    吴中超 Wu Zhongchao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
吴中超 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Cindy    伍桐昕 Wu Tongxin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
伍桐昕 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Clarence 杨皓然 Yang Haoran
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
杨皓然 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Elsa     姚蕴芯 Yao Yunxin
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |
姚蕴芯 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Yanyan   郑颖茵 Zheng Yingyin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
郑颖茵 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Ludi     钟子阳 Zhong Ziyang
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
钟子阳 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Felix    叶梓诚 Ye Zicheng
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
叶梓诚 had no trouble understanding me, spoke correctly with a consistent stammer, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

** A+
*** Daisy     黄嘉雯 Huang Jiawen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
黄嘉雯 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Kerwin   黄彦凯 Huang Yankai
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
黄彦凯 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. He would benefit from graded readers.

*** Darren   刘润明 Liu Runming
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
刘润明 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. He would benefit from graded readers.

*** Amy 莫倩霖 Mo Qianlin
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

莫倩霖 understands most of the material I tested and had no trouble understanding me. She forgot some vocabulary, but it did not hinder her speaking. She would benefit from consuming graded readers and aural practice.

*** Annie    郑奕霏 Zheng Yifei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |
郑奕霏 had no trouble understanding me, spoke rather fluidly, and remembered most vocabulary. She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.
*** Kevin 冯晓光 Feng Xiaoguang
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 3         |
冯晓光 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers.

*** Angeline 许婼晴 Xu Ningqing
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          5 |

许婼晴 had no trouble understanding me or any of the material I tested but she stammered a lot when she spoke and I sometimes had difficulty understanding her. She remembered all the vocabulary, but it took her some time to bring it to mind. She would benefit from more aural practice.

*** Phoebe 易婧纯 Yi Jingchun
| Understanding | Speaking | Vocabulary |
|             5 |        4 |          4 |
易婧纯 had no trouble understanding me or most of the material I tested, but she could not produce much English without resorting to Chinese. The English she produced was fluid, but she falls back to Chinese too easily. She remembered all the vocabulary, but it took her some time to bring it to mind. She would benefit from graded readers and fluency exercises.

** A
*** Hiphop Man 陈元浩 Chen Yuanhao
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          5 |
陈元浩 had a little trouble understanding me without help, spoke rather fluidly, and remembered all vocabulary. He would benefit from graded readers and/or native-level English literature.

*** Cassie    陈雅晴 Chen Yaqing
| Understanding | Speaking | Vocabulary |
|             4 |        5 |          3 |
陈雅晴 had trouble understanding me without some help. She spoke correctly with a persistent stammer. She forgot some vocabulary. She would benefit from aural practice and graded readers.

*** Jenny    周欣雨 Zhou Xinyu
| Understanding | Speaking | Vocabulary |
|             4 |        4 |          3 |

周欣雨 had some trouble understanding me, but she could do it with help. She understood most of the material I tested. She forgot some vocabulary, but her forgetfulness was close (e.g., she mixed up "blind" with "deaf," so she knew the word was related to a sensory disability, she just forgot which was which). She would benefit from consuming graded readers and aural practice.

*** Flower    黄沛菡 Huang Peihan
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          5 |
黄沛菡 had a little trouble understanding me, and she struggled to produce output, but remembered all vocabulary. He would benefit from graded readers.

*** Sophy 张心然 Zhang Xinran
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          4 |

张心然 had some trouble understanding me, but she could do it with help. She understood most of the material I tested. She forgot some vocabulary, and she had some trouble speaking without resorting to Chinese, so she needs more comprehensible input. She would benefit from consuming graded readers and aural practice.

*** Eric     张灏铖 Zhang Haocheng
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          5 |
张灏铖 had some trouble understanding me. He struggled with producing narrative English, but he managed. He remembered all vocabulary. He would benefit from aural practice and graded readers.

*** Terry (Eagle Eyes) 郑毅添 Zheng Yitian
| Understanding | Speaking | Vocabulary |
|             3 |        4 |          3 |

郑毅添 goes by "Eagle Eyes" in my class. He had some trouble understanding me and we had to resort to Chinese a couple of times. He forgot some vocabulary and could not tell me what animal blind people might have, despite knowing the word blind, so I think his issue was misunderstanding my question rather than not knowing the proper word to use. He stammered when he spoke and made many minor grammar errors but with no meaning errors. He would benefit from fluency exercises to build his pattern recognition of some basic English as well as from graded readers for the same reason.

* Class 8
This class has an interesting reverse-bell curve of English ability. Some students excel while other students seem below average as compared to the other 7th graders at this school. There are few students in the middle.

** A++
*** Bobby 杜晋鹏 Du Jinpeng
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

杜晋鹏 had no trouble understanding me or any of the material I tested and spoke rather fluidly, and answered English questions without hesitation. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** David 刁家臻 Diao Jiazhen
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

刁家臻 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Cassie 吴诗媚 Wu Shimei
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

吴诗媚 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She was unconfident in her ability and had something written to refer to while she spoke, but it was clear she did not need it. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Amy 梁康雅 Liang Kangya
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

梁康雅 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Ethan    叶炫廷 Ye Xuanting
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

叶炫廷 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Binbo    林钊冰 Lin Zhaobing
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

林钊冰 had no trouble understanding me or any of the material I tested, though he stammered as he spoke. He would benefit from fluency exercises to improve his confidence and output of spoken English.

*** Fred 何沐宸 He Muchen
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

何沐宸 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He was unconfident in his ability and had something written to refer to while he spoke, but it was clear he did not need it. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Steve 曹开元 Cao Kaiyuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5         |

曹开元 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Yuki 罗雅琪 Luo Yaqi
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

罗雅琪 had no trouble understanding me or any of the material I tested and spoke rather fluidly. She has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Lisa      贺玉菡 He Yuhan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

贺玉菡 had no trouble understanding me, spoke with a small stammer, and remembered all vocabulary. She made some minor meaning mistakes from her attempt at speaking idiomatically, but the idioms were outside the curriculum, so I applaud her for trying and take no points. Specifically, she said "time flies" when she meant to say "time passes" and "play with others" when she meant to say "play with each other." She has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature as well as fluency exercises.

*** Karry 朱颂羽 Zhu Songyu
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
朱颂羽 had little trouble understanding me, spoke with a consistent stammer, and remembered all vocabulary. She would benefit from aural practice and fluency exercises.

*** Sara 卓栩如 Zhuo Xuru
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
卓栩如 had no trouble understanding me, spoke with a consistent stammer, and remembered all vocabulary. She would benefit from more aural practice and fluency exercises.

*** Jack 陈家和 Chen Jiahe
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |
陈家和 had no trouble understanding me, spoke rather fluidly, and remembered all vocabulary. He has reached an intermediate level of English and would benefit from graded readers and/or native-level English literature.

*** Stephen  谭宇昊 Tan Yuhao
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

谭宇昊 had no trouble understanding me and spoke with few stammers. He has reached an intermediate level of English and would benefit from reading graded or native-level English literature.

*** Romeo 罗蜜欧 Romeo
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

罗蜜欧 understands all of the material I tested and had no trouble understanding me, even when I went outside the curriculum. He made only very minor, arbitrary English grammar mistakes when he was making up words, which is an advanced skill for a 7th grader. He did not know the word "imaginative," so he said "imaginacal," which was impressive to me. He would benefit from consuming graded readers and native-level English literature.

*** Wendy 李雯臻 Li Wenzhen
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 5          |

李雯臻 had no trouble understanding me or any of the material. Though she spoke timidly, she did not stammer often. She may have reached an intermediate level of English and would benefit from reading graded readers.

*** Void     潘逸恒 Pan Yiheng
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          5 |

潘逸恒 had no trouble understanding me or any of the material I tested and spoke rather fluidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

** A+
*** Cindy    杨婉煊 Yang Wanxuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

杨婉煊 had no trouble understanding me or most of the material I tested and spoke rather fluidly. She forgot some vocabulary, but it did not hinder her speaking, though she stammered somewhat. She would benefit from graded readers to improve her pattern recognition and fluency exercises to improve her confidence.

*** Yentl    郑颖彤 Zheng Yingtong
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          4 |

郑颖彤 had no trouble understanding me or most of the material I tested, forgetting only a little vocabulary, and spoke fluidly but timidly. He has reached an intermediate level of English and would benefit from reading graded readers or native-level English literature.

*** Aaron    周建安 Zhou Jianan
| Understanding | Speaking | Vocabulary |
|             5 |        4 | 5          |

周建安 had no trouble understanding me or any of the material I tested, though he stammered when he spoke and had to resort to Chinese at the end. He also had to say some of the vocabulary in Chinese before in English to remind himself. He would benefit from fluency exercises to develop his grasp on the flow of English.

*** Cici 余芊芊 Yu Qianqian
| Understanding | Speaking | Vocabulary |
|             5 |        5 | 3         |

余芊芊 had a little trouble understanding me, but only on vocabulary terms; she had some trouble with some of the material. She stammered as she spoke, but she spoke correctly. She would benefit from aural practice and graded readers.

*** Kerwin   周建源 Zhou Jianyuan
| Understanding | Speaking | Vocabulary |
|             5 |        5 |          3 |

周建源 understands most of the material I tested and had no trouble understanding me. He struggles a bit in speaking while trying to remember the words he wants to use or to speak around the words he does not know. When I asked where electricity comes from (seeking "power station" or something similar), he said "from clouds" without much hesitation, which shows he has a good circumlocution ability as that is technically correct. He would benefit from consuming graded readers and more aural practice.

*** Jolyne 李嘉琳 Li Jialin
| Understanding | Speaking | Vocabulary |
|             5 |        4 | 3        |

李嘉琳 had no trouble understanding me or most of the material I tested and spoke with only a slight stammer. She forgot some of the vocabulary, but she was able to speak around her lack of knowledge. She would benefit from graded readers.

*** Alice    彭馨怡 Peng Xinyi
| Understanding | Speaking | Vocabulary |
|             4 |        4 | 4         |
彭馨怡 struggles with producing English, but she understands what I said with some help. She forgot some vocabulary, but she was still able to function without that vocabulary. She would benefit from fluency exercises and graded readers.

** A
*** Susan 涂依依 Tu Yiyi
| Understanding | Speaking | Vocabulary |
|             4 |        3 |          4 |
涂依依 had some trouble understanding me, but could do it with help, she had difficulty with producing output, but I could tell it was largely because of her nerves. She would benefit from aural practice and comprehensible input from basic graded readers.

*** Jerry 刘家玮 Liu Jiawei
| Understanding | Speaking | Vocabulary |
|             3 |        2 | 3         |
刘家玮 struggled to understand me, even with significant help. He did not remember almost any vocabulary I tested. He could not produce almost any English. He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

*** Hao Lin  雷浩林 Lei Haolin
| Understanding | Speaking | Vocabulary |
|             3 |        3 |          3 |
雷浩林 is happy and always well-behaved in class. He likes to show off when he can answer a question I have. I think he would benefit from basic graded readers.

** B
*** Peter    饶润辉 Rao Runhui
| Understanding | Speaking | Vocabulary |
|             3 |        2 |          2 |

饶润辉 could not produce any English, besides "play games", "no", and "what can I say?" (a meme phrase for the 6th and 7th graders). He somewhat understood me with some help, but he could not speak even when someone translated my question to him. He would benefit from remedial English and a lot of comprehensible input in the form of very basic graded readers.

*** Eric Zhuo 卓宇城 Zhuo Yucheng
| Understanding | Speaking | Vocabulary |
|             2 |        3 |          2 |

卓宇城 struggled to understand me, even with significant help. He did not remember most vocabulary I tested. He could not produce very much English. He said only "My friend I play football after school." He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

*** Dong 林博东 Lin Bodong
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          3 |

林博东 struggled to understand me, even with significant help. He did not remember almost any vocabulary I tested. He could not produce almost any English and spoke to me only in Chinese. He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

*** Havid    刘振华 Liu Zhenhua
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          3 |
刘振华 struggled to understand me, even with significant help. He did not remember almost any vocabulary I tested. He could not produce almost any English. He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

*** Eric Gan  甘泽成 Gan Zecheng
| Understanding | Speaking | Vocabulary |
|             2 |        2 |          2 |

甘泽成 struggled to understand me, even with significant help. He did not remember most vocabulary I tested. He could read a sentence I showed him. He could not produce almost any other English. He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

*** Howard    蔡昊燃 Cai Haoran
| Understanding | Speaking | Vocabulary |
|             2 |        2 | 2         |

蔡昊燃 struggled to understand me, even with significant help. He did not remember any vocabulary I tested. He could not produce almost any English, and spoke to me only in Chinese. He would benefit from remedial English with lots of comprehensible input and maybe some very basic graded readers.

* Setup                                            :noexport:
# Local variables:(setq org-export-with-section-numbers nil)
# after-save-hook: org-html-export-to-html
# end:
